### ISSUE TITLE
#65 ⁃ Edits on receiving the decryption key

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#255]
In GitLab by @Sorunome on Nov 24, 2021, 18:45

If you receive the decryption key later than the message while the timeline is open, e.g. via key requests, and said message is an edit, it shows the original message until you re-open the timeline.

# DoR Bug report
- [ ] The issue title and description should be explained in English language.
- [ ] Description of current and expected behavior is understood.
- [ ] If necessary,  reproduction steps should be included.
- [ ] Every attached media (if applicable) includes a short description.
- [ ] Bug can be reproduced in the latest development version
- [ ] Severity is understood.
- [ ] Responsible squad has been identified (issue is labeled)
- [ ] There is a list of affected components if needed.
- [ ] There is an estimate on the effort to fix the bug.

**Comment by krille-chan** [comment]
I can reproduce that it is fixed now. Can be tested with these steps where you need 3 devices:

On device A with account 1:
- Receive Message
- Find out your device ID

On device B with account 1:
- See same message appearing

On device C with account 2:
- Block the device ID of device A
- Send an edit to the message

Now open device A and see that the edit is encrypted. However open now device B and reopen the timeline to see how keys are shared so that device A can see the edit and it gets dynamically added now
